### ISSUE TITLE
Cannot find offsets

### ISSUE THREAD

**Issue by roast247** [hailzfn/IGodsEye-Reborn#2]
What file(s) do I have to update, and I can't find the offsets

**Comment by hailzfn** [comment]
Dynamic.h and look on uc to get offsets

**Comment by hailzfn** [comment]
Also look I uploaded the offsets

**Comment by roast247** [comment]
Thanks bro! Just to be clear all I have to really do is update the offsets and its fine to use?

**Comment by hailzfn** [comment]
And the bone and clientinfo decryptions

**Comment by roast247** [comment]
got it. thanks bro

**Comment by 04255** [comment]
Is there a convenient dumper that can help me？version:1.37.6.9310537

**Comment by hailzfn** [comment]
dude listen to me.
learn how to code ik it seems boring as fuck and it seems like you can just skid of an outdated source and make it work but most cod sources will get you banned as soon as you inject or start it
I used to be like this too  but for the past 3 weeks i've genuinely been trying to learn c++ and I'm not even a quarter of the way to proficient yet. And after you get how to do general c++ it will take longer to get into gamehacking c++ because you are manipulating memory and using drivers.. Also you can read the 120 page thread on the MW forum it will help u out a lot. But the thing that helps the most is genuinely trying to learn c++.  I don't want to be the jackass dude that says "Oh learn to code first" But its true. Learning to code will help you a lot. I am nowhere near a pro I've only been seriously learning for about 3 weeks. But I have a lot of basic c++ knowledge now and it is helping me understand what the hack I'm seeing on github is doing. and still there is much to learn for me

**Comment by 04255** [comment]
"it seems like you can just skid of an outdated source and make it work but most cod sources will get you banned as soon as you inject or start it"yes,It's like licking the cake on his knife
I've been a csgo hacker before and it works very well,It gave me blind confidence
In the past week, I have suffered a lot from BE BAN
It seems that there is no room for external programs to survive here.
However, my knowledge is only about external programs, and I don't know anything about internal injection
Do you have any suggestions on the direction of learning, or suggest that I give up the game?

**Comment by 04255** [comment]
Is the source code of this injection program still working? If I want to escape punishment, what should I do? I used to be a rash boy, but the hateful war zone has brought me too many lessons.
I hope to listen to your experience as a past person. If I can learn internal programs from this source code, is it possible for me to succeed? I'm completely disappointed. 
The  battle eye is too vicious,I don't even have to wait to know that for beginners, challenging the battle eye is a dead end.
Maybe you have experienced my despair, I don't know how to support my learning motivation.

Anyway, thank you for your company, stranger. Maybe I will give up this game. But any help you give me is worth being appreciated. Learning alone may be boring and boring. Maybe we can become friends and learn coding / reverse together

**Comment by hailzfn** [comment]
The actual drawing and math code still works but the decryption and all the other stuff is outdated and the methods changed
